PHPLIB-1350 Add tests on Date Expression Operators
mongodb/mongo-php-builder pull request #34
Opened 2024-01-18 14:07 UTC by GromNaN

Fix [PHPLIB-1350](https://jira.mongodb.org/browse/PHPLIB-1350)

https://www.mongodb.com/docs/manual/reference/operator/aggregation/#date-expression-operators

- `$dateAdd`
- `$dateDiff`
- `$dateFromParts`
- `$dateFromString`
- `$dateSubtract`
- `$dateToParts`
- `$dateToString`
- `$dateTrunc`
- `$dayOfMonth`
- `$dayOfWeek`
- `$dayOfYear`
- `$hour`
- `$isoDayOfWeek`
- `$isoWeek`
- `$isoWeekYear`
- `$millisecond`
- `$minute`
- `$month`
- `$second`
- `$toDate`
- `$week`
- `$year`

2024-01-18 14:11 UTC, GromNaN commented on generator/config/expression/dateFromString.yaml
> +                            onNull: 1970-01-01T00:00:00+00:00
I tried to represent the date using the Extended JSON format: `{ $date: 0 }`, but this get converted to `{ $date: { $numberInt: 0 } }` and the date is actually represented with a long `{ $date: { $numberLong: 0 } }`.

So I ended using Yaml date, that why I configured the parser to parse dates, and added a transformation pass using `array_walk_recursive` to convert `DateTimeInterface` into `MongoDB\BSON\UTCDateTime`.

2024-01-18 14:14 UTC, GromNaN commented on generator/config/expression/dayOfMonth.yaml
> +                            date: '$date'
The [example](https://www.mongodb.com/docs/manual/reference/operator/aggregation/dayOfMonth/#example) is the same for all this date part operators. So I picked only the tested operator for each.

2024-01-18 17:09 UTC, GromNaN commented on tests/Builder/Expression/DateAddOperatorTest.php
> +                    unit: 'day',
It would be very useful to have a enum for this units. https://jira.mongodb.org/browse/PHPLIB-1370

2024-01-19 08:18 UTC, alcaeus requested changes

2024-01-19 08:18 UTC, alcaeus commented on generator/config/expression/dateAdd.yaml
> +                # $merge: 'shipping'
Noted you left a comment denoting the original since our `$merge` operator always uses the `into` argument.

2024-01-19 08:18 UTC, alcaeus commented on generator/src/OperatorTestGenerator.php
> +            });
This looks like it's left over from before extracting `convertTypeRecursively`.

2024-01-19 08:18 UTC, alcaeus commented on generator/config/expression/dateFromString.yaml
> +                            onNull: 1970-01-01T00:00:00+00:00
Just adding a note that we can leverage a custom tag for this if we run into issues with the automatic parsing of dates when we don't expect it: https://symfony.com/doc/current/components/yaml.html#parsing-and-dumping-custom-tags

2024-01-19 10:38 UTC, GromNaN commented on generator/src/OperatorTestGenerator.php
> +            });
Removed, thanks.

2024-01-19 10:39 UTC, GromNaN commented on generator/config/expression/dateFromString.yaml
> +                            onNull: 1970-01-01T00:00:00+00:00
I switched all specific BSON types to Yaml tags. That's more explicit.

2024-01-19 11:17 UTC, GromNaN commented
Added support for `!date 0` Yaml tag, and `!binary 'base64'` for https://github.com/mongodb/mongo-php-builder/pull/37#discussion_r1458006767

2024-01-19 12:07 UTC, alcaeus approved these changes
Yaml tags look a lot better, great work!

2024-01-19 13:44 UTC, GromNaN commented on generator/config/expression/dateAdd.yaml
> +                # $merge: 'shipping'
I did this in few other place. So that if we find there is a bug, it's easier to see the original example.

2024-01-19 13:47 UTC, merged